### ISSUE TITLE
サイドバーにて送信者一覧を表すコンポーネントの作成

### ISSUE THREAD

**Issue by Wansuko-cmd** [prapro-ou/castella-frontend#2]
# 概要
<img width="378" alt="スクリーンショット 2023-07-24 21 01 14" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/547c7696-9ab6-4041-90ef-bcdf4d7f545c">

上のコンポーネントを実装する

### コンポーネント名

DestinationList

### 引数

計画中・・・

|  引数名  |  内容  |
| ---- | ---- |
| destinations | メッセージ内容 |
| onClickAddButton | プラスボタンを押されたときに実行する関数 |

### 書く場所

`features/talks/components`

###  注意点

- `feature/talks/destinations/components`にある`DestinationTile`を使うこと
- 今回は「DM」のところは埋め込みでOK

**Comment by KitauchiRyota** [comment]
細かいことで申し訳ありませんが，作成にあたっていくつか疑問・要望があるので解答していただけると幸いです．

1.  引数の欄に「計画中・・・」とありますが，何か変更がございますか．

2. 仕様について，可能であればもう少し詳しく書いていただけると取り組みやすくて非常に助かります．具体的には，引数`destination`の処理で何をすればよいのかがわかりません．

3.  「`feature/talks/components`にある`MessagePartnerTile`を使うこと」とありますが，使用するものについては`DestinationTile`のことでよろしかったでしょうか．（それと，この`feature/talks/components`というパスは実際は違う名前になっているような気がします・・・）

4. 以前に自分が作った`DestinationTile`のPRでも少し触れましたが，現状だと未読件数が0のときでも**0の未読アイコンが表示**されると思います．解決自体は`messageCount`が0の時は実行しない，というようにすればすぐできると思いますが，この方針で修正してもよろしいでしょうか．またその場合，`DestinationTile`と`UnreadMessgeCount`のどちらの機能にすればよいでしょうか．

お忙しい中お手数をおかけしますが，どうかよろしくお願いします．

**Comment by Wansuko-cmd** [comment]
1. 変更なし・・・だが引数とかがまだ確定してないので考えてもらいたい
2. 前まで作ってもらってたDestinationTileの引数・・・の配列を渡してほしい
3. DestinationTileであってる（急に作りすぎていろいろ変になってる。ごめん）
4. 0の時に実行しない・・・というよりは1以上の時に出すようにしてくれたら助かる。やるならDestinationTileに書く方がいいかも
