### ISSUE TITLE
スレッドを表すコンポーネント

### ISSUE THREAD

**Issue by Wansuko-cmd** [prapro-ou/castella-frontend#31]
# 概要

<img width="471" alt="スクリーンショット 2023-08-05 11 55 43" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/755a3c87-b632-4126-903e-efe3113cf296">

上記のコンポーネントを作成する
引数によって文字は濃くなったり（default）薄くなったり(thin)・・・

# 実装の流れ

### コンポーネント名

ThreadTile

### 引数

|  引数名  |  内容  |
| ---- | ---- |
| subject | 件名 |
| body | 内容 |
| message_count | 返信数 |
| is_new | 新着かどうか |
| onClickMessageCount | 「n件の返信」が押された時の挙動 |

### 書く場所

`features/talks/threads/components`

###  注意点

- onClickMessageCountについては() -> void型でいい
-  Reactのイベント処理について書かれた記事を参考に書くと良さそう（例：https://qiita.com/jima-r20/items/839da7c2f26366491298）

**Comment by Yuto-Kambara** [comment]
質問です。
画面が変化するのはn件の返信の部分を押したときだけで灰色の部分に関しては押しても何も起こらない感じでしょうか。

**Comment by Wansuko-cmd** [comment]
> 画面が変化するのはn件の返信の部分を押した時だけ？

その認識で大丈夫

> 灰色の部分が緑になるなどの処理は・・・

ごめん、この部分が抜けてた
`selected`という引数を追加して、これがtrueの時は色を変える感じにしてもらえると！

**Comment by Yuto-Kambara** [comment]
ありがとうございます。あと件数の部分の色を青色にしたいのですがその場合はtailwind.config.jsに色を追加すれば良いでしょうか。

**Comment by Wansuko-cmd** [comment]
そう、色は追加して欲しい
とりあえずurlという名前で頼む

**Comment by Wansuko-cmd** [comment]
カードの幅は一旦固定で頼む

**Comment by Yuto-Kambara** [comment]
了解です､そのように作成します。
