### ISSUE TITLE
ローディング画面をDestinationsに適用する

### ISSUE THREAD

**Issue by Wansuko-cmd** [prapro-ou/castella-frontend#57]
# 概要

画面中央、右側の要素が読み込まれている間にローディングを入れたい（下のような奴）

![image](https://github.com/prapro-ou/castella-frontend/assets/63241922/2720ff22-ff70-4b2a-96fb-51aa2848a1e0)

# 実装の流れ

今回はライブラリの選定からやってみてもらいたい（分からんてなったら質問投げてくれ）

1. ~ ライブラリを探して導入 ~
2. ~ ローディングを出してみる ~
3. 通信中だけローディングを出してみる（ローディング中だけtrueになるようなStateを作成する）

基本的に、ローディングのグルグルは画面の区切りごとに出してもらいたいと考えてる（スレッドを読み込み中ならスレッドのところだけ・・・みたいな）

### コンポーネント名

LoadingScreen

### 引数

isLoading: Loading中かどうか

### 書く所

`features/components` でよさそう

### 期限

8/23 の昼までに完成を目指してほしい
間に合わなさそうなら事前に連絡を入れてほしい

### 注意点

分からんかったら質問投げてくれ

**Comment by Wansuko-cmd** [comment]
それで大丈夫そう

**Comment by Wansuko-cmd** [comment]
スピナーの種類多いからそこだけ気を付けてもらえればOK!

**Comment by Jaja-UMA** [comment]
Ovalでいこうと思ってますがどうでしょう

**Comment by Jaja-UMA** [comment]
通信中だけローディングを出してみる（ローディング中だけtrueになるようなStateを作成する）

この部分に関してなんですが，引数のisLoadingがtrueのときに，
trueとなるような変数をuseStateを用いてつくればいいのでしょうか．

**Comment by Wansuko-cmd** [comment]
どういう意味だろう？
必要なのはStateを作ること
そのStateは、通信中はtrueになってて、通信が済めばfalseになること
通信中かどうかの判別はuseDataのAPIを呼び出すタイミングから判断する
こんな感じやな
