### ISSUE TITLE
登録画面のデザイン

### ISSUE THREAD

**Issue by Wansuko-cmd** [prapro-ou/castella-frontend#59]
# 概要

こういうのが組めたらかっこいい・・・と思いたい

![image](https://github.com/prapro-ou/castella-frontend/assets/63241922/81420c1a-ea6b-45cf-87ef-a5feadb676c5)

今回はMaterial DesiginのDialogのデザインをそのまま流用する形の方が早くてよさげ？

# 実装の流れ

app/register/page.jsの中身をいじる

送信したときにLoadingを出したいがこれはLoadingのタスクが終わった後でやろう

# 期日

8/23 12:00までにお願いしたい

**Comment by KitauchiRyota** [comment]
`app/layout.js`のレイアウトをこのページに適用させないようにするにはどうすればよいでしょうか．自分でも調べてみましたがうまくできませんでした．

**Comment by Wansuko-cmd** [comment]
というより、layoutの中身を別に移動させる方がベストだと思う
Headerの事？

**Comment by Wansuko-cmd** [comment]
基本的に今回のHeaderはアプリ本体以外では必要ないからそっちに移動させるのはあり

**Comment by Wansuko-cmd** [comment]
その時はHeaderはコンポーネント化してfeatures/compnentsに入れてもらえると

**Comment by KitauchiRyota** [comment]
そのあたりのことがやはりよくわからなかったので，とりあえずそこ以外を作ったもので一旦PR作成しました．
概要の画像の左半分のデザインは未実装です．

**Comment by KitauchiRyota** [comment]
一応ヘッダーを消した状態で再現してみました．
レイアウトの適用範囲を変えれば以下のようになると思います．
![スクリーンショット (766)](https://github.com/prapro-ou/castella-frontend/assets/136436225/3d6b8659-76e3-4b1b-bc5a-69a8529f5218)
