### ISSUE TITLE
アイコンコンポーネントの作成

### ISSUE THREAD

**Issue by Wansuko-cmd** [prapro-ou/castella-frontend#7]
# 概要
<img width="74" alt="スクリーンショット 2023-07-25 0 33 05" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/d8975feb-629d-4035-b54e-26e373b22b09">

上記アイコンコンポーネントを作成する

# 実装の流れ

### コンポーネント名

Icon

### 引数

|  引数名  |  内容  |
| ---- | ---- |
| src | アイコンの画像 |
| alt | 画像が表示されなかった場合に表示される文字 |

### 書く場所
`features/components`

###  注意点

- サイズは24pxで作成すること（後日別のコンポーネントを作成した後に調節する予定）
- `src`が渡されなかった（undefindだった場合）は上の写真のアイコンを表示するようにすること

**Comment by Yuto-Kambara** [comment]
すみません､完成したのですがどうやってpushするのか忘れてしまったので教えてもらえませんか?

**Comment by Wansuko-cmd** [comment]
```
git add .
git commit -m "コミットメッセージ（[add] Iconコンポーネントを追加、等）"
git push origin ブランチ名
```
これでpushできます

**Comment by Wansuko-cmd** [comment]
その後は　[Pull Request](https://github.com/prapro-ou/castella-frontend/pulls)からプルリクエストを作成してください。
![image](https://github.com/prapro-ou/castella-frontend/assets/63241922/e953c2c4-4418-47b4-99fc-c7d12b60c5b4)

**Comment by Yuto-Kambara** [comment]
ブランチ名を忘れてしまってgit rev-parse --abbrev-ref HEADというコマンドで現在のブランチ名を調べるとmainと出てきたのですがこれはブランチがうまく生成できていなかったりするのでしょうか。

**Comment by Wansuko-cmd** [comment]
今のブランチおよび作成してるブランチは
```
git branch
```
で確認できる

```
$git branch
  feature/vector
  iotype
* main
  vectortemp
  viktor
```

**Comment by Wansuko-cmd** [comment]
もしブランチがmainなら
```
git checkout -b feature/icon-component
```
と打って見て
変わるばず

**Comment by Yuto-Kambara** [comment]
ありがとうございます。pull requestのところまで進められたと思うのですが正しく行えていますでしょうか?

**Comment by Wansuko-cmd** [comment]
これでpull requestは作れると思う

**Comment by Wansuko-cmd** [comment]
![image](https://github.com/prapro-ou/castella-frontend/assets/63241922/5f8be673-6a71-4fd9-b980-c34fcbd4c04e)
ここで右下のボタンを押して

![image](https://github.com/prapro-ou/castella-frontend/assets/63241922/4931222d-8fba-415c-8eff-87b905426c16)
ここでCreate Pull Requestボタンを押せばできる

その後で出てくる画面でメッセージを記述する形でお願いします

**Comment by Yuto-Kambara** [comment]
了解です。ありがとうございます。
